// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujnephrnnltdhepqrxms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqbmVwaHJubmx0ZGhlcHFyeG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODMwNjIsImV4cCI6MjA3MzM1OTA2Mn0.l8fV4ygF6T0B75APT2Q07VwE9Na1V_vQRR6XwucDMok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});